//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaOdontologica.Desfalcados.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int ID_CARGO { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public decimal VL_SALARIO { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public bool FL_DENTISTA { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public int ID_ESPECIALIZACAO { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string NOME { get; set; }
    
        public virtual Especializacao Especializacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
