//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaOdontologica.Desfalcados.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int ID_FUNCIONARIO { get; set; }

        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string NOME { get; set; }
        public int ID_CARGO { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string CPF { get; set; }
        public string CRO { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string SEXO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual Cargo Cargo { get; set; }
    }
}
