//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaOdontologica.Desfalcados.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int ID_PACIENTE { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string NOME { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string CPF { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string NOME_MAE { get; set; }
        public string NOME_PAI { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public int IDADE { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string GENERO { get; set; }
        public Nullable<int> ID_CONVENIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual Convenio Convenio { get; set; }
    }
}
