//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaOdontologica.Desfalcados.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servico()
        {
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int ID_SERVICO { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public string SERVICO1 { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public decimal VALOR { get; set; }
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public int ID_ESPECIALIZACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual Especializacao Especializacao { get; set; }
    }
}
