//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaOdontologica.Desfalcados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UsuarioID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool active { get; set; }
        public System.DateTime DateADD { get; set; }
        public int UserADD { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public Nullable<int> UserDelete { get; set; }
    }
}
